name: tests
on:
  pull_request:
  push:
    branches: [ master ]

  schedule:
  - cron: '25 08 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This is required for "gautamkrishnar/keepalive-workflow", see "ddev/github-action-add-on-test"
permissions:
  actions: write

jobs:
  tests:
    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ env.GITHUB_REPOSITORY }}
          addon_ref: ${{ env.GITHUB_REF }}

      - name: Wait for Directus service to be healthy
        run: |
          for i in {1..12}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' $(docker-compose ps -q directus))
            echo "Directus service health status: $STATUS"
            if [ "$STATUS" == "healthy" ]; then
              echo "Directus service is healthy."
              break
            elif [ "$STATUS" == "unhealthy" ]; then
              echo "Directus service is unhealthy. Exiting."
              exit 1
            else
              echo "Directus service is still starting. Waiting..."
              sleep 10
            fi
          done

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Fetch Directus service logs
        if: ${{ failure() }}
        run: |
          echo "Fetching logs for DDev Directus service..."
          ddev logs -s directus

      - name: Fetch Directus service logs
        if: ${{ failure() }}
        run: |
          echo "Fetching logs for Directus service..."
          docker logs $(docker-compose ps -q directus)

      - name: Fetch Directus service health details
        if: ${{ failure() }}
        run: |
          echo "Fetching health details for Directus service..."
          docker inspect --format "{{ json .State.Health }}" $(docker-compose ps -q directus) | jq
